steps:
  - label: "Validate package.json"
    command: make validate-dependencies
    plugins:
      -  automattic/bash-cache#2.12.0

  - label: "Install Dependencies"
    command: .buildkite/commands/install-dependencies.sh
    plugins:
      -  automattic/bash-cache#2.12.0

  # - group: "iOS"
  #   steps:
  #   - label: "Bundle iOS for Testing"
  #     command: make bundle-ios-for-testing
  #     plugins:
  #       -  automattic/bash-cache#2.12.0
  #     agents:
  #       queue: "js"

  #   - label: "iOS JS Tests"
  #     command: make test-ios
  #     plugins:
  #       -  automattic/bash-cache#2.12.0
  #     artifact_paths:
  #       - "reports/**/*"

  #   - label: "Build iOS Test App"
  #     command: .buildkite/commands/build-mac-bundle.sh
  #     key: build-ios-test-app
  #     env:
  #       IMAGE_ID: xcode-13.4.1
  #     plugins:
  #       -  automattic/bash-cache#2.12.0
  #     agents:
  #       queue: "mac"
  #     artifact_paths:
  #       - artifacts/GutenbergDemo.app.zip

  # - group: "Android"
  #   steps:
  #   - label: "Android JS Tests"
  #     command: make test-android
  #     plugins:
  #       -  automattic/bash-cache#2.12.0
  #     artifact_paths:
  #       - "reports/**/*"

  #   - label: "Build and Test Android Editor"
  #     command: |
  #       make install-dependencies
  #       cd gutenberg/packages/react-native-editor/android && ./gradlew testDebug
  #     agents:
  #       queue: "android"

  #   - label: "Build and Test Bridge Editor"
  #     command: cd gutenberg/packages/react-native-bridge/android && ./gradlew test
  #     agents:
  #       queue: "android"

  #   - label: "Android e2e Tests"
  #     command: |
  #       make build-android-for-testing
  #       make e2e-test-android
  #     plugins:
  #       -  automattic/bash-cache#2.12.0
  #     artifact_paths:
  #       - "reports/**/*"

  # - group: "Publish"
  #   steps:
  #   - label: "Bundle Android for Release"
  #     key: "bundle-android"
  #     command: |
  #       make bundle-android
  #       buildkite-agent artifact upload bundle/android/App.js

  #   - label: "Build Android RN Aztec & Publish to S3"
  #     key: "publish-react-native-aztec-android"
  #     command: .buildkite/publish-react-native-aztec-android-artifacts.sh
  #     plugins:
  #       -  automattic/bash-cache#2.12.0
  #     agents:
  #       queue: "android"

  #   - label: "Build Android RN Bridge & Publish to S3"
  #     depends_on:
  #       - "bundle-android"
  #       - "publish-react-native-aztec-android"
  #     command: .buildkite/publish-react-native-bridge-android-artifacts.sh
  #     plugins:
  #       -  automattic/bash-cache#2.12.0
  #     agents:
  #       queue: "android"
