x-common-params:
  &publish-android-artifacts-docker-container
  docker#v3.8.0:
    image: "public.ecr.aws/automattic/android-build-image:v1.1.0"
    propagate-environment: true
    environment:
      # DO NOT MANUALLY SET THESE VALUES!
      # They are passed from the Buildkite agent to the Docker container
      - "AWS_ACCESS_KEY"
      - "AWS_SECRET_KEY"

steps:
  - label: "Validate package.json"
    command: |
      restore_cache "$BUILDKITE_PIPELINE_SLUG-npm-cache"
      make validate-dependencies
      save_cache .npm-cache "$BUILDKITE_PIPELINE_SLUG-npm-cache"
    plugins:
      -  automattic/bash-cache#2.2.0

  - label: "Test iOS"
    command: |
      restore_cache "$BUILDKITE_PIPELINE_SLUG-npm-cache"
      make test-ios
      save_cache .npm-cache "$BUILDKITE_PIPELINE_SLUG-npm-cache"
    plugins:
      -  automattic/bash-cache#2.2.0

  - label: "Test Android"
    command: |
      restore_cache "$BUILDKITE_PIPELINE_SLUG-npm-cache"
      make test-android
      save_cache .npm-cache "$BUILDKITE_PIPELINE_SLUG-npm-cache"
    plugins:
      -  automattic/bash-cache#2.2.0

  - label: "Build and Test Android Editor"
    command: cd gutenberg/packages/react-native-editor/android && ./gradlew testDebug
    agents:
      queue: "android"

  - label: "Build and Test Bridge Editor"
    command: cd gutenberg/packages/react-native-bridge/android && ./gradlew test
    agents:
      queue: "android"

  - label: "Bundle Android"
    key: "bundle-android"
    plugins:
      - docker#v3.8.0:
          image: "public.ecr.aws/automattic/gb-mobile-image:latest"
          environment:
            - "CI=true"
            # Allow WP-CLI to be run as root, otherwise it throws an exception.
            # Reference: https://git.io/J9q2S
            - "WP_CLI_ALLOW_ROOT=true"
    command: |
        source /root/.bashrc

        nvm install && nvm use
        npm ci --unsafe-perm --prefer-offline --no-audit --no-progress

        npm run prebundle:js
        npm run bundle:android

        buildkite-agent artifact upload bundle/android/App.js

  - label: "Build Android RN Aztec & Publish to S3"
    key: "publish-react-native-aztec-android"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
        .buildkite/publish-react-native-aztec-android-artifacts.sh

  - label: "Build Android RN Bridge & Publish to S3"
    depends_on:
      - "bundle-android"
      - "publish-react-native-aztec-android"
    plugins:
      - *publish-android-artifacts-docker-container
    command: |
        .buildkite/publish-react-native-bridge-android-artifacts.sh
